Added new classes and tests
Angelina2412/java-shareit pull request #2
Opened 2024-12-21 09:10 UTC by Angelina2412

2024-12-22 07:29 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/exceptions/GlobalExceptionHandler.java
> +        Map<String, String> errors = new HashMap<>();
Лучше сделать классик ErrorResponse и отдавать его вместо обезличенного Map.
В ResponseEntity тоже нет необходимости, статусы можно задать аннотациями.
Плюс в обработчик ошибок имеет смыс добавить логирование, это облегчит работу над ошибками.

2024-12-22 07:31 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/exceptions/GlobalExceptionHandler.java
> +}
Нужно добавить метод обработки всех оставшихся и неидентифицированных ошибок Throwable в статус INTERNAL_SERVER_ERROR

2024-12-22 07:32 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final String userId = "X-Sharer-User-Id";
лучше static т.к. общая константа для всех экземпляров класса

2024-12-22 07:35 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<ItemDto> addItem(@Valid @RequestHeader(userId) Long ownerId,
`@Valid` нужно только на типы, где на полях используются аннотации валидации, в нашем случае это Dto. У  Long нет ни поле ни соответственно аннотаций, поэтому `@Valid` на нем излишен

2024-12-22 07:37 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (!userService.existsById(ownerId)) {
Такие проверки относятся к бизнес-логике, поэтому их лучше разместить в самих методах классов-сервисов

2024-12-22 07:39 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<ItemDto> updateItem(@Valid @RequestHeader(userId) Long ownerId,
ResponseEntity в контроллерах в нашем проекте избыточен. Можно отдавать просто Dto а статус задать аннотацией.

2024-12-22 07:44 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<?> createUser(@Valid @RequestBody User user) {
Для юзеров тоже нужно исползовать Dto

2024-12-22 07:47 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        boolean emailExists = userService.getAllUsers().stream()
Проверки надо разместить в классе-сервисе. В случае не успеха выбрасывать исключение, затем его ловить и обрабатывать в нужный статус в глобальном оработчике ошибок. На данном курсе такая стратегия.

2024-12-22 07:48 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        user.setId(idGenerator.incrementAndGet());
Генерация ИД - зона ответственноси класса-сервиса

2024-12-22 07:49 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +public class UserService {
Для единообразия с остальными пакетам сделай интерфейс и реализацию

2024-12-22 07:50 UTC, VadimZharkov requested changes
Можно улучшить.

2024-12-23 16:52 UTC, Angelina2412 commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +public class UserService {
сделала

2024-12-23 16:59 UTC, Angelina2412 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        user.setId(idGenerator.incrementAndGet());
Исправила

2024-12-23 17:25 UTC, Angelina2412 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        boolean emailExists = userService.getAllUsers().stream()
Исправила

2024-12-23 17:32 UTC, Angelina2412 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<?> createUser(@Valid @RequestBody User user) {
Исправила

2024-12-24 05:56 UTC, Angelina2412 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<ItemDto> updateItem(@Valid @RequestHeader(userId) Long ownerId,
Исправила

2024-12-24 05:58 UTC, Angelina2412 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (!userService.existsById(ownerId)) {
Исправила

2024-12-24 05:59 UTC, Angelina2412 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<ItemDto> addItem(@Valid @RequestHeader(userId) Long ownerId,
Исправила

2024-12-24 06:00 UTC, Angelina2412 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final String userId = "X-Sharer-User-Id";
Исправила

2024-12-24 06:04 UTC, Angelina2412 commented on src/main/java/ru/practicum/shareit/exceptions/GlobalExceptionHandler.java
> +}
Исправила

2024-12-25 07:45 UTC, VadimZharkov approved these changes

2025-02-28 15:48 UTC, merged